import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";
import path from "path";
import { radFishThemePlugin, getDefaultConfig } from "./plugins/vite-plugin-radfish-theme.js";

/**
 * RADFish Theme Configuration
 *
 * IMPORTANT: Change theme settings in ONE place:
 *   themes/noaa-theme/styles/theme.scss
 *
 * The radFishThemePlugin automatically:
 *   - Parses theme.scss and generates _uswds-generated.scss
 *   - Injects CSS variables into index.html
 *   - Updates index.html meta tags
 *   - Provides values to PWA manifest (below)
 *
 * Usage:
 *   radFishThemePlugin("noaa-theme")                 // Use default NOAA theme
 *   radFishThemePlugin("noaa-theme", { app: {...} }) // With app config overrides
 *
 * Available themes (in themes/ folder):
 *   - noaa-theme: Default NOAA branding with USWDS colors
 */

// Get default config (includes parsed colors as fallback)
const defaultConfig = getDefaultConfig();

// Define config overrides here (app name, description)
// NOTE: Colors automatically come from themes/<theme-name>/styles/theme.scss (Section 1)
const configOverrides = {
  app: {
    name: "Fish Tracker",
    shortName: "FishTrack",
    description: "Track and manage fish catch data",
  },
  pwa: {
    // NOTE: The PWA manifest theme_color is dynamically generated by radFishThemePlugin
    // It reads the actual color from themes/<theme-name>/styles/theme.scss (Section 1)
    // The defaultConfig.colors.primary below is just a fallback used during config parsing
    // In dev mode: manifest.json is served via configureServer hook with parsed colors
    // In build: manifest.json is written via closeBundle hook with parsed colors
    themeColor: defaultConfig.colors.primary,
  },
};

export default defineConfig({
  base: "/",
  resolve: {
    alias: {
      '@theme': path.resolve(__dirname, 'themes/noaa-theme/styles'),
    },
  },
  css: {
    preprocessorOptions: {
      scss: {
        includePaths: ["node_modules/@uswds/uswds/packages"],
        // Suppress USWDS deprecation warnings about global built-in functions
        // These are from USWDS using map-merge() which will be fixed in Dart Sass 3.0.0
        quietDeps: true,
      },
    },
  },
  plugins: [
    // RADFish theme plugin - provides:
    // - import.meta.env.RADFISH_* constants
    // - CSS variable injection
    // - manifest.json generation on build
    radFishThemePlugin("noaa-theme", configOverrides),
    react(),
    // VitePWA for service worker
    VitePWA({
      devOptions: {
        enabled: process.env.NODE_ENV === "development",
        type: "module",
      },
      registerType: "autoUpdate",
      injectRegister: null,
      strategies: "injectManifest",
      srcDir: "src",
      filename: "service-worker.js",
      // Manifest configuration (synced with radFishThemePlugin configOverrides)
      manifest: {
        short_name: configOverrides.app.shortName,
        name: configOverrides.app.name,
        description: configOverrides.app.description,
        start_url: "/",
        display: "standalone",
        scope: "/",
        theme_color: configOverrides.pwa.themeColor,
        background_color: "#ffffff",
      },
    }),
  ],
  server: {
    open: true,
    port: 3000,
  },
  test: {
    globals: true,
    setupFiles: "./src/__tests__/setup.js",
    environment: "jsdom",
  },
});
